export const SUPPORTED_CONNECTORS = [
  {
    id: '1',
    name: 'Snowflake',
    description: 'Connect your Snowflake data warehouse for instant AI analysis',
    type: 'Data Warehouse',
    icon: 'database',
    status: 'disconnected',
  },
  {
    id: '2',
    name: 'MySQL',
    description: 'Connect your MySQL database for instant AI analysis',
    type: 'Database',
    icon: 'server',
    status: 'disconnected',
  },
  {
    id: '3',
    name: 'MSSQL',
    description: 'Connect your Microsoft SQL Server for instant AI analysis',
    type: 'Database',
    icon: 'server',
    status: 'disconnected',
  },
  {
    id: '4',
    name: 'PostgreSQL',
    description: 'Connect your PostgreSQL database for instant AI analysis',
    type: 'Database',
    icon: 'database',
    status: 'disconnected',
  },
  {
    id: '5',
    name: 'Google Sheets',
    description: 'Connect your Google Sheets to query and analyze spreadsheet data with AI',
    type: 'Integration',
    icon: 'table',
    status: 'disconnected',
  },
  {
    id: '6',
    name: 'Web Search using LLM',
    description: 'Query the web using large language models to fetch and analyze live data',
    type: 'Integration',
    icon: 'globe',
    status: 'disconnected',
  },
  {
    id: '7',
    name: 'Upload CSV File',
    description: 'Upload one or more CSV files to instantly analyze and query your tabular data with AI',
    type: 'File Upload',
    icon: 'csv',
    status: 'disconnected',
  },
  {
    id: '8',
    name: 'Upload SQL File',
    description: 'Upload one or more SQL dump files to run queries and gain insights from your database exports',
    type: 'File Upload',
    icon: 'sql',
    status: 'disconnected',
  },
  // ─── NEW ───────────────────────────────────────────────────────────────────
  {
    id: '9',
    name: 'FTP Connector',
    description: 'Connect to an FTP server to fetch files with incremental progress tracking and scheduled sync',
    type: 'Integration',
    icon: 'ftp',
    status: 'disconnected',
  },
  {
    id: '10',
    name: 'Upload Document',
    description: 'Upload PDF, DOC, or DOCX files for AI analysis',
    type: 'File Upload',
    icon: 'file-text',
    status: 'disconnected',
  },
  // ─── Tally ERP ─────────────────────────────────────────────────────────────
  {
    id: '11',
    name: 'Tally ERP',
    description: 'Connect to your Tally ERP server to fetch accounting, inventory and financial data via XML API',
    type: 'Integration',
    icon: 'tally',
    status: 'disconnected',
  },
];
